### ISSUE TITLE
[Bug] every call create a new user although there is an existing user

### ISSUE THREAD

**Issue by AlexD1979** [voicefoundryap/amazon-connect-for-zendesk#69] opened 2021-05-04 10:25 UTC
**Describe the bug**
An already known user are re-created every time the user calls Amazon Connect and opens a ticket in Zendesk. 
The user entry can be found in Zendesk with exact matching phone number.

**To Reproduce**
1. Call the inbound number with a desk phone
2. The call will be routed to an agent and rings
3. A new ticket opens AND a window new user opens

Additional informations: The existing user contact has multiple contact entires and the calling number for our test is not the first one in the list, it is the 2nd.. Does Zendesk / CTI Adapter got issues with multiple phone numbers on an existing contact?

**Expected behavior**
As described in the documentation for 2.2.2, if an user already exists, then open only a new (or recent) ticket and DOES NOT create a new user entry.

**Screenshots**
No, GDPR compliant informations not to be shown herer.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version latest

**Comment by robert-leafworks** [comment] 2021-05-05 10:48
We experienced the same Issue and figured out when this happens...

Just to give you a hint what we figured out:

There are users with same phone-numbers and all records have the shared_phone_number = 1
When this occurs a new User will be created everytime the number calls and creates doublettes.
We have a phone-only requester where the user was definetely created by the App. I am not sure how this happens because via the zendesk interface it's not possible to create this scenario. It could be an issue in the App or even an issue on Zendesk side. 

At the moment we have around 40 records with a lot of doubled-user records in the system. To deal with this there is the need to merge all these users + fix the bug that this won't happen anymore. 

Best,
Robert

**Comment by AlexD1979** [comment] 2021-05-06 10:08
Hello Robert,
Thanks to the quick response.

We digg deeper in the case and can give you additional informations:


  *   When a user has multiple user account with different user_ids but the same telephone number, the adapter failst o identify the user. What is your idea behind this szenario to solve?
  *   If you have only a single user with one phone number the adapter und user identification works fine
  *   If Zendesk have one user, with muliple phone numbers, does your adapter choose by which logic the right phone number for identification?

As you spoke about a bug in the CTI Adapter, which options do we have together with you to solve the bug shortly?


Mit freundlichen Grüßen / Best regards

tecRacer GmbH & Co. KG
Alexander Diedler
Team Amazon Connect
Certified IT Business Manager
Vahrenwalder Str. 156
30165 Hannover, Germany

Telefon: +49 511 59095 919
Mobil: +49 175 5214838
E-Mail: ***@***.******@***.***>
Internet: https://connect.tecracer.de/

Registergericht Hannover HRA 200331
Geschäftsführer: Markus P. Herrlich, Sven Ramuschkat, Torsten Höpfner
Komplementär: tecRacer Verwaltungs GmbH, Hannover HRB 200935

[signature_1667064984]





Von: robert-leafworks ***@***.***>
Gesendet: Mittwoch, 5. Mai 2021 12:49
An: voicefoundryap/amazon-connect-for-zendesk ***@***.***>
Cc: Alexander Diedler ***@***.***>; Author ***@***.***>
Betreff: Re: [voicefoundryap/amazon-connect-for-zendesk] [Bug] every call create a new user although there is an existing user (#69)


We experienced the same Issue and figured out when this happens...

Just to give you a hint what we figured out:

There are users with same phone-numbers and all records have the shared_phone_number = 1
When this occurs a new User will be created everytime the number calls and creates doublettes.
We have a phone-only requester where the user was definetely created by the App. I am not sure how this happens because via the zendesk interface it's not possible to create this scenario. It could be an issue in the App or even an issue on Zendesk side.

At the moment we have around 40 records with a lot of doubled-user records in the system. To deal with this there is the need to merge all these users + fix the bug that this won't happen anymore.

Best,
Robert

-

**Comment by agroblervf** [comment] 2021-06-09 02:09
Sorry for a late reply.

Confirming this is a bug when a user has multiple numbers and it's due to the way Zendesk updates a user record when a new phone number has been added. The latest added number will be stored in the `phone` field of the user record and the `shared_phone_number` may be set to true, if another user already has that number as the direct line. Zendesk user search will still return the record but as the shared attribute is turned on it will be filtered out by the app. 
To fix this we will need to combine the user search with user identities crosscheck, to retrieve a proper user.
This fix should be available in the next service release.

**Comment by AlexD1979** [comment] 2021-06-09 07:15
Hello,
Thank you to clarify this point. When is the planned next service release?
Best regards
Alexander

**Comment by agroblervf** [comment] 2021-06-10 05:54
@AlexD1979 We haven't got the confirmed date for the next service release yet.
Fix has been applied and tested internally and then merged to the Develop branch. Suggest you create a private app from this branch, including files and folders as described [here](https://github.com/voicefoundryap/amazon-connect-for-zendesk#making-and-installing-your-private-zendesk-app) and then test it in your non-prod environment. If you're happy with the fix, you can then install and switch to this private app in your production until the service release.

**Closed** 2022-01-31 12:01 UTC
